### PR TITLE
Merge upstream dashboard master into our fork

### PR DESCRIPTION
**Pull request by dylanrhodes**
This PR includes changes made to the analytics dashboard over the past year or so.  It brings our fork roughly up to date with upstream's 0.13.0-rc.1 release, although a few additional bug fixes for that release candidate are also included.  There have been many changes made to the dashboard over the past year, including a new layout, video analytics, and new performance/grading data.  The new appearance and features of the dashboard can be seen on the stage instance, which has been running this branch for a few days without issues.  The last three commits listed here are the only new ones made, but there are a lot of changes to the code base included overall. @stvstnfrd @dcadams

### CODE REVIEW

**Comment by stvstnfrd** [comment]
+1

**Comment by stvstnfrd** [comment]
@dcadams Any input on this?

**Comment by dcadams** [comment]
:+1: if it all works on stage.

**Comment by stvstnfrd** [comment]
@dylanrhodes Fire when ready.

**Pull request merged**
