### PR TITLE
Merge most recent release from edx

### PR DESCRIPTION
**Pull request by dylanrhodes**
This PR pulls in missing features from the upstream dashboard repository.  It is based off of the 0.7.0 release from upstream (<a href="https://github.com/edx/edx-analytics-dashboard/commit/3ae7920680cef7cb3df1295c5343823f21a8408b">here</a>) which is the most recent.  I'm not totally sure why it includes commits from so far back (several from November).  It may be that we just haven't done a full merge of Insights since then. @stvstnfrd

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@dylanrhodes Hrm, yeah, there really isn't any merit in attempting to parse this manually; too much going on.

But since this repo has a `.travis.yml`, can you look into enabling Travis integration for this repo? I'll feel much more comfortable once we're running CI tests against this.

Give a holler if you need a hand w/ that.

**Comment by stvstnfrd** [comment]
Can this be discarded in favor of #2 ?

**Comment by stvstnfrd** [comment]
@dylanrhodes post-break ping

**Comment by dylanrhodes** [comment]
@stvstnfrd Yes, this branch has been superceded by #2 but I'd like to keep it open until that one is merged.  I'll take care of closing it afterwards.

**Comment by stvstnfrd** [comment]
sgtm @dylanrhodes

**Comment by stvstnfrd** [comment]
@dylanrhodes Can we kill this now?

Hoping to clean up the master PR list ;)

**Comment by dylanrhodes** [comment]
@stvstnfrd yes, I'll go ahead and close it.

**Pull request closed without merging**
