### PR TITLE
Dcadams/merge/candidate

### PR DESCRIPTION
**Pull request by dcadams**
Merge of upstream at a79929951f90a1de0fa51c416a129e6cc72adc69

### CODE REVIEW

**Comment by dcadams** [comment]
@stv this code is already running on CME.

**Comment by dcadams** [comment]
@stvstnfrd this code is already running on CME.

**Review by stvstnfrd — COMMENTED** [review]
Looks good, just a few questions:
- Presumably no worries for compatibility w/r/t Lagunita/SUclass, just a matter of doing the dance and installing the code there too, right?
- I ran a `diff` of this branch against the upstream merge point and it looks like we haven't forked this with custom changes; does that sound right?

**Comment by stvstnfrd** [comment]
I just took a look at the what's changed since this merge and the current `upstream/master` [1].
Looks like it's really just updated translations. The only code changes are some minor bumps of Python libraries (from `requirements.txt`) and one timeout value [2] was increased from 5 seconds to 10 (by default).

I'm thinking right after we merge this, we should just pull in `upstream/master` too and be all caught up on this repo.

[1]  `git diff a79929951f90a1de0fa51c416a129e6cc72adc69..upstream/master`
[2] `ANALYTICS_API_DEFAULT_TIMEOUT`

**Comment by stvstnfrd** [comment]
@dcadams I also went ahead and enabled travis-ci integration for this repo, since it hadn't been yet.

You'll probably need to either push this branch again or maybe even close then reopen the PR to trigger a build.

**Comment by dcadams** [comment]
Lagunita is running origin/dylanrhodes/merge_upstream
Suclass is running origin/release

In any event, they shouldn't be affected.

We did have some forks but they disappeared along the way.

Edx have actually started using named releases for analytics branches now and I tried to go with ginko for CME. Only problem was it wouldn't install due to some wacky webpack error so I went with head, at the time, where it had been fixed. I'm inclined to leave as-is for now and update everything to Hawthorn once it gets released.

**Pull request merged**
